Repository CS2103-AY1819S1-W17-1/main, pull requests merged in 2018-10, with the labels that each got.

#22 Update User Guide and Developers Guide
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/UIMockup_20180925.png
  docs/images/Ui.png
Labels: docs

#12 [v1.1][W17-1] tag related documentation changes
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: docs

#30 Update docs and UI mockup
  docs/DeveloperGuide.adoc
  docs/UiMockup.pptx
  docs/UserGuide.adoc
  docs/images/Ui.png
Labels: docs

#32 Documentation update
  docs/UserGuide.adoc
Labels: docs

#33 Import markdown library
  build.gradle
Labels: Enhancement

#47 Update AboutUs
  docs/AboutUs.adoc
Labels: Task, docs

#48 Add entry related classes
  src/main/java/seedu/address/model/entry/Address.java
  src/main/java/seedu/address/model/entry/Email.java
  src/main/java/seedu/address/model/entry/EntryDescription.java
  src/main/java/seedu/address/model/entry/EntryInfo.java
  src/main/java/seedu/address/model/entry/MajorResumeEntry.java
  src/main/java/seedu/address/model/entry/Name.java
  src/main/java/seedu/address/model/entry/PersonalInfo.java
  src/main/java/seedu/address/model/entry/Phone.java
  src/main/java/seedu/address/model/entry/Taggable.java
  src/main/java/seedu/address/model/entry/exceptions/DuplicateEntryException.java
  src/main/java/seedu/address/model/entry/exceptions/EntryNotFoundException.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/model/entry/AddressTest.java
  src/test/java/seedu/address/model/entry/EmailTest.java
  src/test/java/seedu/address/model/entry/EntryDescriptionTest.java
  src/test/java/seedu/address/model/entry/EntryTest.java
  src/test/java/seedu/address/model/entry/NameTest.java
  src/test/java/seedu/address/model/entry/PersonalInfoTest.java
  src/test/java/seedu/address/model/entry/PhoneTest.java
  src/test/java/seedu/address/testutil/EntryBuilder.java
  src/test/java/seedu/address/testutil/TypicalEntrys.java
Labels: wip

#54 documentation for categories, part of #29
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/shupeng.adoc
Labels: status.ReadyForReview

#98 Add ContextCommand and related tests
  src/main/java/seedu/address/logic/commands/ContextCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ContextCommandParser.java
  src/test/java/seedu/address/logic/commands/ContextCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ContextCommandParserTest.java
Labels: status.ReadyForReview

#110 Fix naming from MajorResumeEntry to ResumeEntry
  src/main/java/seedu/address/model/entry/UniqueEntryList.java
  src/test/java/seedu/address/model/entry/UniqueEntryListTest.java
Labels: status.ReadyForReview

#101 add config for reposense
  _reposense/config.json
Labels: status.ReadyForReview

#70 Add LoadTemplateCommand and support in Model and Storage
  src/main/java/seedu/address/commons/events/model/TemplateLoadRequestedEvent.java
  src/main/java/seedu/address/logic/commands/LoadTemplateCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/template/Template.java
  src/main/java/seedu/address/model/template/TemplateSection.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TemplateStorage.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEntryCommandTest.java
Labels: status.ReadyForReview

#100 Add sample slang - full phrase mappings + related tests
  src/main/java/seedu/address/model/Awareness.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/AwarenessTest.java
Labels: status.ReadyForReview

#114 Create EntryBook
  src/main/java/seedu/address/model/EntryBook.java
  src/main/java/seedu/address/model/ReadOnlyEntryBook.java
  src/main/java/seedu/address/model/entry/UniqueEntryList.java
  src/test/java/seedu/address/model/EntryBookTest.java
  src/test/java/seedu/address/model/entry/EntryTest.java
  src/test/java/seedu/address/testutil/EntryBookBuilder.java
  src/test/java/seedu/address/testutil/TypicalEntrys.java
Labels: status.ReadyForReview

#112 Add Markdown Generator utility class
  src/main/java/seedu/address/model/MarkdownConverter.java
  src/test/java/seedu/address/model/MarkdownConverterTest.java
Labels: status.ReadyForReview

#115 Link Awareness into Model and Logic
  src/main/java/seedu/address/logic/commands/ContextCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEntryCommandTest.java
Labels: status.ReadyForReview

#127 Update format of EntryInfo display
  src/main/java/seedu/address/storage/util/MarkdownConverter.java
  src/test/java/seedu/address/storage/util/MarkdownConverterTest.java
Labels: priority.Low, status.ReadyForReview

#131 Add versioned address book
  src/main/java/seedu/address/model/VersionedEntryBook.java
  src/test/java/seedu/address/model/VersionedEntryBookTest.java
Labels: status.ReadyForReview

#133 Add Resume-related classes
  src/main/java/seedu/address/model/resume/Resume.java
  src/main/java/seedu/address/model/resume/ResumeHeader.java
  src/main/java/seedu/address/model/resume/ResumeSection.java
  src/main/java/seedu/address/storage/util/MarkdownConverter.java
  src/test/java/seedu/address/model/resume/ResumeTest.java
  src/test/java/seedu/address/storage/util/MarkdownConverterTest.java
Labels: priority.High, status.ReadyForReview

#137 Change LoadTemplateCommand execution message
  src/main/java/seedu/address/logic/commands/LoadTemplateCommand.java
Labels: status.ReadyForReview

#139 Add docs for template
  docs/DeveloperGuide.adoc
Labels: docs

#146 Update docs for Resume generation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: docs, status.ReadyForReview

#143 Update UG
  docs/UserGuide.adoc
Labels: docs, priority.High, status.ReadyForReview

#147 Update DG
  docs/DeveloperGuide.adoc
  docs/images/classDiagramForEntry.png
Labels: docs, status.ReadyForReview

#148 Add loadtemplate to command summary
  docs/UserGuide.adoc
Labels: docs

#149 Error correction in UG
  docs/UserGuide.adoc
Labels: docs

#153 tag manager for filtering entries
  src/main/java/seedu/address/model/entry/ResumeEntry.java
  src/main/java/seedu/address/model/tag/ContainsTagsPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/TagManager.java
  src/test/java/seedu/address/model/tag/TagManagerTest.java
Labels: status.ReadyForReview

#160 Update config names
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
Labels: status.ReadyForReview

#154 cleanup before addentry
  src/main/java/seedu/address/logic/commands/AddEntryCommand.java
  src/main/java/seedu/address/logic/parser/AddEntryCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: status.ReadyForReview

#161 Add intro to DG
  docs/DeveloperGuide.adoc
Labels: docs, status.ReadyForReview

#156 Add further support for Resume in the Model
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/resume/Resume.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEntryCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/resume/ResumeTest.java
  src/test/java/seedu/address/storage/util/MarkdownConverterTest.java
Labels: priority.Medium, status.ReadyForReview

#163 Update Template error handling flow
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TemplateStorage.java
  src/main/java/seedu/address/storage/TxtTemplateStorage.java
Labels: status.ReadyForReview

#166 Add description of template file format to UG
  docs/UserGuide.adoc
Labels: docs

#167 Add Event Name --> ResumeEntry TreeMap + Validation for slang
  src/main/java/seedu/address/model/Awareness.java
  src/test/java/seedu/address/model/AwarenessTest.java
Labels: status.Ongoing

#152 add category manager to filter out entries
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/category/CategoryManager.java
  src/main/java/seedu/address/model/category/ContainsCategoryPredicate.java
  src/test/java/seedu/address/model/category/CategoryManagerTest.java
  src/test/java/seedu/address/model/category/ContainsCategoryPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalEntrys.java
Labels: status.ReadyForReview

#150 Modify ug after peer review
  docs/UserGuide.adoc
Labels: docs

#165 Complete add entry
  src/main/java/seedu/address/logic/commands/AddEntryCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
Labels: status.ReadyForReview

#170 updated dev docs to include details on categorymanager
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/categoryManager.xml
  docs/images/categoryManager_example_listEntry.png
  docs/images/categoryManager_example_template.png
Labels: status.ReadyForReview

#171 add func to allow Model to get full list
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: status.ReadyForReview

#183 Minor addition to string util
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
Labels: status.ReadyForReview

#182 refactor category to extend from tag
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/model/category/Category.java
  src/main/java/seedu/address/model/category/CategoryManager.java
  src/main/java/seedu/address/model/entry/ResumeEntry.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/TagManager.java
  src/test/java/seedu/address/model/category/CategoryManagerTest.java
  src/test/java/seedu/address/model/entry/EntryTest.java
  src/test/java/seedu/address/model/tag/TagManagerTest.java
  src/test/java/seedu/address/testutil/TypicalEntrys.java
Labels: status.ReadyForReview

#174 create the tag command sub parser #173
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
Labels: status.ReadyForReview

#188 Update names in UserPrefs production / test files
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: status.ReadyForReview

#178 Display entry in ui
  src/main/java/seedu/address/ui/EntryCard.java
  src/main/java/seedu/address/ui/EntryListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/EntryListCard.fxml
  src/main/resources/view/EntryListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/EntryCardHandle.java
  src/test/java/guitests/guihandles/EntryListPanelHandle.java
  src/test/java/seedu/address/ui/EntryCardTest.java
  src/test/java/seedu/address/ui/EntryListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: priority.High, status.ReadyForReview

#179 Add support to add ResumeEntries based on possibleEventName
  src/main/java/seedu/address/logic/commands/ContextCommand.java
  src/main/java/seedu/address/model/Awareness.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/ContextCommandTest.java
Labels: status.ReadyForReview

#189 Add Make command
  src/main/java/seedu/address/logic/commands/MakeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MakeCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/MakeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/MakeCommandParserTest.java
Labels: priority.High, status.Ongoing

#191 Implementing addBullet command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddBulletCommand.java
  src/main/java/seedu/address/logic/parser/AddBulletCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entry/ResumeEntry.java
  src/test/java/seedu/address/logic/commands/AddBulletCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddBulletCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/entry/EntryTest.java
  src/test/java/seedu/address/testutil/EntryBuilder.java
Labels: status.ReadyForReview

#196 Move entry builder to production code
  src/main/java/seedu/address/model/util/EntryBuilder.java
  src/test/java/seedu/address/logic/commands/AddBulletCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/AddEntryCommandParserTest.java
  src/test/java/seedu/address/model/EntryBookTest.java
  src/test/java/seedu/address/model/category/ContainsCategoryPredicateTest.java
  src/test/java/seedu/address/model/entry/EntryInfoTest.java
  src/test/java/seedu/address/model/entry/EntryTest.java
  src/test/java/seedu/address/testutil/TypicalEntrys.java
  src/test/java/seedu/address/ui/EntryCardTest.java
Labels: status.ReadyForReview

#197 Add sample pre filled entries
  src/main/java/seedu/address/model/Awareness.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/ContextCommandTest.java
Labels: status.ReadyForReview

#203 Resume Storage component
  src/main/java/seedu/address/commons/exceptions/MarkdownProcessingException.java
  src/main/java/seedu/address/commons/util/MdUtil.java
  src/main/java/seedu/address/storage/MarkdownResumeStorage.java
  src/main/java/seedu/address/storage/MdFileStorage.java
  src/main/java/seedu/address/storage/ResumeStorage.java
  src/main/java/seedu/address/storage/util/MarkdownConverter.java
  src/test/java/seedu/address/storage/MarkdownResumeStorageTest.java
Labels: priority.High, status.ReadyForReview

#200 Implement Select Entry
  src/main/java/seedu/address/commons/events/ui/JumpToEntryListRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/UpdateExpandedEntryRequestEvent.java
  src/main/java/seedu/address/logic/commands/SelectEntryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SelectEntryCommandParser.java
  src/main/java/seedu/address/model/entry/EntryDescription.java
  src/main/java/seedu/address/model/util/EntryBuilder.java
  src/main/java/seedu/address/ui/EntryListPanel.java
  src/main/java/seedu/address/ui/ExpandedEntryPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ExpandedEntryPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/ExpandedEntryPanelHandle.java
  src/test/java/seedu/address/commons/TestForSelfAddedEvents.java
  src/test/java/seedu/address/logic/commands/SelectEntryCommandParserTest.java
  src/test/java/seedu/address/logic/commands/SelectEntryCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/entry/EntryDescriptionTest.java
  src/test/java/seedu/address/testutil/TypicalEntryDescription.java
  src/test/java/seedu/address/testutil/TypicalEntrys.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/ui/EntryListPanelTest.java
  src/test/java/seedu/address/ui/ExpandedEntryPanelTest.java
Labels: status.ReadyForReview, type.Enhancement

#205 Update UI to display loaded Template
  src/main/java/seedu/address/logic/commands/LoadTemplateCommand.java
  src/main/java/seedu/address/model/template/Template.java
  src/main/java/seedu/address/storage/TxtTemplateStorage.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TemplatePanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TemplatePanel.fxml
Labels: status.ReadyForReview

#193 create tag list cmd
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/TagListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/logic/parser/TagListCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/TagListCommandTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TagListCommandParserTest.java
  src/test/java/seedu/address/model/EntryBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/TypicalEntrys.java
Labels: status.ReadyForReview

#206 AddBulletCommand: allow it to raise relevant events for UI components…
  src/main/java/seedu/address/logic/commands/AddBulletCommand.java
Labels: type.Enhancement

#199 Add context bar
  src/main/java/seedu/address/commons/events/ui/ContextUpdateEvent.java
  src/main/java/seedu/address/ui/ContextBar.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/ContextBar.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: status.ReadyForReview

#209 Update versioning
  src/main/java/seedu/address/MainApp.java
Labels: priority.High, status.ReadyForReview

#212 Complete resume feature
  src/main/java/seedu/address/commons/events/model/ResumeSaveEvent.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/resume/Resume.java
  src/main/java/seedu/address/storage/MarkdownResumeStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/util/MarkdownConverter.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/resume/ResumeTest.java
  src/test/java/seedu/address/storage/util/MarkdownConverterTest.java
  src/test/java/seedu/address/testutil/TypicalResumeModel.java
Labels: priority.High, status.Ongoing

#211 Update user guide
  docs/UserGuide.adoc
Labels: priority.High, status.ReadyForReview

#217 Update UG/DG for Templates
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/images/Template_SD1.png
  docs/images/Template_SD2.png
  docs/images/Template_UML.png
  src/main/java/seedu/address/commons/events/ui/NewResultAvailableEvent.java
Labels: docs

#221 Update UI image in main page
  docs/images/Ui.png
Labels: docs, status.ReadyForReview

#223 Move Awareness into sub package
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/awareness/Awareness.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/AwarenessStorage.java
  src/main/java/seedu/address/storage/XmlAwarenessStorage.java
  src/main/java/seedu/address/storage/XmlSerializableAwareness.java
  src/test/java/seedu/address/model/AwarenessTest.java
Labels: status.ReadyForReview
