Repository CS2103-AY1819S1-W17-1/main, pull requests merged in 2018-11, with the labels that each got.

#234 Update UG/DG for resume generation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: docs, priority.Medium, status.ReadyForReview

#232 Update dg
  docs/DeveloperGuide.adoc
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/images/SequenceDiagramAddBullet_1.png
  docs/images/SequenceDiagramAddBullet_2.png
  docs/images/classDiagramForEntry.png
  docs/team/hengyuan.adoc
Labels: docs

#230 Update ug
  docs/UserGuide.adoc
Labels: docs

#226 Update manual testing instructions
  docs/DeveloperGuide.adoc
Labels: status.ReadyForReview

#231 Create CommandLineObserver and link with Awareness
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/observers/AwarenessService.java
  src/main/java/seedu/address/logic/observers/CmdLineObserver.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/logic/observers/AwarenessServiceTest.java
Labels: status.ReadyForReview

#220 Override equals() in Template and TemplateSection
  src/main/java/seedu/address/model/template/Template.java
  src/main/java/seedu/address/model/template/TemplateSection.java
Labels: status.ReadyForReview

#228 tag add command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/TagAddCommand.java
  src/main/java/seedu/address/logic/parser/TagAddCommandParser.java
  src/test/java/seedu/address/logic/commands/TagAddCommandTest.java
  src/test/java/seedu/address/logic/parser/TagAddCommandParserTest.java
Labels: status.ReadyForReview

#263 tag rt cmd
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/TagRetagCommand.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/logic/parser/TagRetagCommandParser.java
  src/test/java/seedu/address/logic/commands/TagRetagCommandTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TagRetagCommandParserTest.java
Labels: status.ReadyForReview

#253 Add entry storage
  src/main/java/seedu/address/storage/entry/XmlAdaptedEntryDescription.java
  src/main/java/seedu/address/storage/entry/XmlAdaptedEntryInfo.java
  src/main/java/seedu/address/storage/entry/XmlAdaptedResumeEntry.java
  src/main/java/seedu/address/storage/entry/XmlSerializableEntryBook.java
  src/test/java/seedu/address/storage/entry/XmlSerializableEntryBookTest.java
Labels: priority.High, status.ReadyForReview

#246 tag rm cmd
  src/main/java/seedu/address/logic/commands/TagRmCommand.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/logic/parser/TagRmCommandParser.java
  src/test/java/seedu/address/logic/commands/TagRmCommandTest.java
  src/test/java/seedu/address/logic/parser/TagRmCommandParserTest.java
Labels: status.ReadyForReview

#266 Link awareness with ModelManager constructor
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/awareness/Awareness.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddBulletCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ContextCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/TagAddCommandTest.java
  src/test/java/seedu/address/logic/commands/TagListCommandTest.java
  src/test/java/seedu/address/logic/commands/TagRetagCommandTest.java
  src/test/java/seedu/address/logic/commands/TagRmCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/observers/AwarenessServiceTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: status.ReadyForReview

#275 Update UG for Template, Tags
  docs/UserGuide.adoc
Labels: docs, status.ReadyForReview

#279 Rename PPP files
  docs/team/anubh-v.adoc
  docs/team/jhengy.adoc
  docs/team/marvintxd.adoc
  docs/team/ongspxm.adoc
  docs/team/scalarmotion.adoc
Labels: docs, status.ReadyForReview

#276 Implementing EditEntryInfo Command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EditEntryInfoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditEntryInfoCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/entry/EntryInfo.java
  src/test/data/XmlSerializableEntryBookTest/typicalEntryBook.xml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditEntryInfoCommandTest.java
  src/test/java/seedu/address/logic/commands/TagListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditEntryInfoCommandParserTest.java
  src/test/java/seedu/address/model/EntryBookTest.java
  src/test/java/seedu/address/testutil/TypicalEntrys.java
Labels: status.ReadyForReview, type.Enhancement

#268 Allow Template loading to account for different exception types; add template related tests
  src/main/java/seedu/address/commons/exceptions/InvalidTemplateFileException.java
  src/main/java/seedu/address/logic/commands/LoadTemplateCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/template/Template.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TemplateStorage.java
  src/main/java/seedu/address/storage/TxtTemplateStorage.java
  src/test/java/seedu/address/model/template/TemplateTest.java
Labels: status.ReadyForReview

#270 ModelManager and Model: deleteEntry() method
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/exceptions/DeleteEntryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteEntryCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteEntryCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteEntryCommandParserTest.java
Labels: status.ReadyForReview, type.Enhancement

#282 Trigger EntryBook loading in MainApp
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/entry/EntryBookStorage.java
  src/main/java/seedu/address/storage/entry/XmlEntryBookStorage.java
Labels: status.ReadyForReview

#287 add tag add cmd
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
Labels: status.ReadyForReview

#280 Allow storage of user particulars, to be displayed in the resume
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserParticulars.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEntryCommandTest.java
Labels: status.ReadyForReview

#291 Fix error under edit info command test
  src/main/java/seedu/address/model/entry/EntryDescription.java
  src/main/java/seedu/address/model/entry/ResumeEntry.java
Labels: status.ReadyForReview, type.Bug

#293 Finish Awareness refactoring (to use Dictionary)
  src/main/java/seedu/address/model/awareness/Awareness.java
  src/main/java/seedu/address/model/awareness/Dictionary.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/AwarenessTest.java
  src/test/java/seedu/address/model/awareness/DictionaryTest.java
Labels: status.ReadyForReview

#286 Minor Changes in UI for Product Demo Dry Run
  src/main/java/seedu/address/logic/commands/AddBulletCommand.java
  src/main/java/seedu/address/ui/EntryCard.java
  src/main/java/seedu/address/ui/ExpandedEntryPanel.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EntryListCard.fxml
  src/test/java/guitests/guihandles/EntryCardHandle.java
Labels: status.ReadyForReview, type.Enhancement

#305 Remove illegal fields from sample entries
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Bug

#304 EntryBuilder Cannot Set Invalid Fields for EntryInfo
  src/main/java/seedu/address/model/entry/EntryInfo.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Bugfix

#289 Awareness serialization
  src/main/java/seedu/address/storage/AwarenessStorage.java
  src/main/java/seedu/address/storage/XmlAdaptedContextEntry.java
  src/main/java/seedu/address/storage/XmlAwarenessStorage.java
  src/main/java/seedu/address/storage/XmlMapping.java
  src/main/java/seedu/address/storage/XmlSerializableAwareness.java
  src/test/java/seedu/address/storage/awareness/XmlSerializableAwarenessTest.java
Labels: status.ReadyForReview

#312 Use correct link to app icon
  README.adoc
  copyright.txt
Labels: docs, status.ReadyForReview, type.Bugfix

#307 Add header to Resume
  src/main/java/seedu/address/model/resume/Resume.java
  src/main/java/seedu/address/model/resume/ResumeHeader.java
  src/main/java/seedu/address/storage/util/MarkdownConverter.java
  src/test/java/seedu/address/storage/util/MarkdownConverterTest.java
Labels: priority.High, status.ReadyForReview

#301 Set up saving of EntryBook to XML; standardized EntryBook/Storage classes with AB4
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
  src/main/java/seedu/address/storage/entry/EntryBookStorage.java
  src/main/java/seedu/address/storage/entry/XmlAdaptedEntryDescription.java
  src/main/java/seedu/address/storage/entry/XmlAdaptedEntryInfo.java
  src/main/java/seedu/address/storage/entry/XmlAdaptedResumeEntry.java
  src/main/java/seedu/address/storage/entry/XmlEntryBookStorage.java
  src/main/java/seedu/address/storage/entry/XmlSerializableEntryBook.java
  src/test/data/XmlEntryBookStorageTest/NotXmlFormatEntryBook.xml
  src/test/data/XmlEntryBookStorageTest/invalidAndValidEntryEntryBook.xml
  src/test/data/XmlEntryBookStorageTest/invalidEntryEntryBook.xml
  src/test/data/XmlSerializableEntryBookTest/invalidCategory.xml
  src/test/data/XmlSerializableEntryBookTest/invalidTag.xml
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/entry/XmlEntryBookStorageTest.java
  src/test/java/seedu/address/storage/entry/XmlSerializableEntryBookTest.java
  src/test/java/seedu/address/testutil/TypicalEntrys.java
Labels: status.ReadyForReview

#302 Ui add header modify expanded entry panel
  src/main/java/seedu/address/model/entry/EntryInfo.java
  src/main/java/seedu/address/model/entry/ResumeEntry.java
  src/main/java/seedu/address/ui/ExpandedEntryPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EntryListPanel.fxml
  src/main/resources/view/ExpandedEntryPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TemplatePanel.fxml
  src/test/java/seedu/address/model/entry/EntryTest.java
  src/test/java/seedu/address/ui/ExpandedEntryPanelTest.java
Labels: status.ReadyForReview, type.Enhancement

#314 Fix Context bar "lagging" by one character
  src/main/java/seedu/address/ui/CommandBox.java
Labels: status.ReadyForReview, type.Bugfix

#299 Add validation for XmlAdaptedEntryDesc + tests for XmlAdaptedEntryInfo / XmlAdaptedEntryDesc
  src/main/java/seedu/address/storage/entry/XmlAdaptedEntryDescription.java
  src/main/java/seedu/address/storage/entry/XmlAdaptedEntryInfo.java
  src/test/java/seedu/address/storage/entry/XmlAdaptedEntryInfoTest.java
  src/test/java/seedu/address/storage/entry/XmlAdaptedResumeEntryDescriptionTest.java
  src/test/java/seedu/address/storage/entry/XmlSerializableEntryBookTest.java
Labels: status.ReadyForReview

#320 Make EntryBook save to XML in respond to changes
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
Labels: status.ReadyForReview

#318 Add tests for template command and parser
  src/main/java/seedu/address/logic/commands/LoadTemplateCommand.java
  src/test/java/seedu/address/logic/commands/LoadTemplateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/LoadTemplateCommandParserTest.java
Labels: status.ReadyForReview

#321 AddBulletCommand modification and some minor modification
  src/main/java/seedu/address/logic/commands/AddBulletCommand.java
  src/main/java/seedu/address/model/EntryBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entry/EntryDescription.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/entry/XmlSerializableEntryBook.java
  src/test/java/seedu/address/logic/commands/AddBulletCommandTest.java
  src/test/java/seedu/address/model/EntryBookTest.java
  src/test/java/seedu/address/storage/entry/XmlEntryBookStorageTest.java
  src/test/java/seedu/address/testutil/EntryBookBuilder.java
  src/test/java/seedu/address/testutil/TypicalEntrys.java
Labels: status.ReadyForReview, type.Bugfix, type.Enhancement

#328 Fix panels not filling the entire stack pane
  src/main/resources/view/ExpandedEntryPanel.fxml
  src/main/resources/view/TemplatePanel.fxml
Labels: status.ReadyForReview, type.Bugfix

#322 Fix empty string bug + Improve code style in Dictionary
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/awareness/Dictionary.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/model/awareness/DictionaryTest.java
Labels: status.ReadyForReview, type.Bugfix

#324 Fix awareness observer parsing bug + clearer message for user + related tests
  src/main/java/seedu/address/logic/observers/AwarenessService.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/awareness/Awareness.java
  src/test/java/seedu/address/logic/observers/AwarenessServiceTest.java
  src/test/java/seedu/address/model/awareness/AwarenessTest.java
Labels: severity.High, status.ReadyForReview, type.Bugfix

#292 Devdocs
  docs/DeveloperGuide.adoc
  docs/team/ongspxm.adoc
Labels: docs, status.ReadyForReview

#331 Update "Coming in v1.4"
  docs/UserGuide.adoc
Labels: docs, status.ReadyForReview

#332 Update DG
  docs/DeveloperGuide.adoc
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/images/SequenceDiagramAddBullet_2.png
Labels: docs, status.ReadyForReview

#333 Devdocs
  docs/UserGuide.adoc
Labels: docs

#337 Update ppp
  docs/images/FlowDiagramForEntryManagement.png
  docs/team/jhengy.adoc
Labels: docs, status.ReadyForReview

#330 Template storage tests
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/model/ResumeSaveEvent.java
  src/main/java/seedu/address/commons/events/model/TemplateLoadRequestedEvent.java
  src/main/java/seedu/address/commons/events/storage/TemplateLoadedEvent.java
  src/main/java/seedu/address/commons/events/storage/TemplateLoadingExceptionEvent.java
  src/main/java/seedu/address/logic/commands/LoadTemplateCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/template/Template.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TxtTemplateStorage.java
  src/test/data/TxtTemplateStorageTest/blankFile.txt
  src/test/data/TxtTemplateStorageTest/invalidRowsTemplate.txt
  src/test/data/TxtTemplateStorageTest/randomFormatTemplate.txt
  src/test/data/TxtTemplateStorageTest/validAndInvalidRowsTemplate.txt
  src/test/data/TxtTemplateStorageTest/validTemplate.txt
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/LoadTemplateCommandTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/MarkdownResumeStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/template/TxtTemplateStorageTest.java
Labels: status.ReadyForReview

#325 Add diagrams and update documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/generateResumeSequenceDiagram.png
  docs/images/resumeClassDiagram.png
  docs/images/resumeStorageExtensionClassDiagram.png
  docs/images/ugTypicalFlowDiagram.png
  docs/team/scalarmotion.adoc
Labels: docs, priority.Medium, status.ReadyForReview

#316 Finish resume-related tests
  src/main/java/seedu/address/model/resume/Resume.java
  src/main/java/seedu/address/model/resume/ResumeHeader.java
  src/main/java/seedu/address/storage/MdFileStorage.java
  src/test/java/seedu/address/logic/commands/MakeCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/resume/ResumeTest.java
  src/test/java/seedu/address/storage/MarkdownResumeStorageTest.java
  src/test/java/seedu/address/storage/util/MarkdownConverterTest.java
  src/test/java/seedu/address/testutil/TypicalResumeModel.java
  src/test/java/seedu/address/testutil/UserParticularsModel.java
Labels: priority.High, status.ReadyForReview

#326 Update template docs and PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/marvintxd.adoc
Labels: docs, status.ReadyForReview

#336 Update DG / PPP for awareness / anubhav
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/awarenessFlow.xml
  docs/diagrams/awarenessHighLevelSeq.xml
  docs/diagrams/awarenessStructure.xml
  docs/images/awarenessFlow.png
  docs/images/awarenessHighLevelSeq.png
  docs/images/awarenessStructure.png
  docs/team/anubh-v.adoc
Labels: docs, status.ReadyForReview

#338 Update component diagrams and manual testing instructions
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ArchitectureDiagram.pptx
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/Architecture.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/TemplateStorage Sequence Diagram.png
  docs/images/Template_SD2.png
  docs/images/UiClassDiagram.png
Labels: docs, status.ReadyForReview

#341 Fix command strings
  src/main/java/seedu/address/logic/commands/TagAddCommand.java
  src/main/java/seedu/address/logic/commands/TagListCommand.java
  src/main/java/seedu/address/logic/commands/TagRetagCommand.java
  src/main/java/seedu/address/logic/commands/TagRmCommand.java
Labels: priority.High, status.ReadyForReview
